language: node_js
node_js:
  - "node"
addons:
  code_climate:
    repo_token: 7f8d94846d5649bfe0e012b010d566b411d01d99355b51c44d4c4934fcf2e790
script: yarn run build
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < ./reports/coverage/lcov.info
  - bash travis-after-build.sh
